#!/bin/bash

INPUT_FILE="data.json"

name=$(jq -r '.name' "$INPUT_FILE")
height=$(jq -r '.height' "$INPUT_FILE")
weight=$(jq -r '.weight' "$INPUT_FILE")
type=$(jq -r '.types[0].type.name' "$INPUT_FILE")

# Height in decimetres -> metres
formatted_height=$(awk "BEGIN {print $height/10}")
# Weight in hectograms -> kilograms
formatted_weight=$(awk "BEGIN {print $weight/10}")

echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."
